### ISSUE TITLE
coverage "No source for code:" error

### ISSUE THREAD

**Issue by lbignone** [cjolowicz/cookiecutter-hypermodern-python#1011]
I am having some trouble with the coverage session in github-actions for my project. I am getting the following error

```
No source for code: '/Users/runner/work/galaxies_datasets/galaxies_datasets/src/galaxies_datasets/__init__.py'.
Aborting report output, consider using -i.
```
even thought that `__init__.py` file does exists. 

Any insight would be greatly appreciated

![Selection_005](https://user-images.githubusercontent.com/8226790/134429401-8343118a-484d-4d4e-84d0-47fedd1684f8.png)

This is the link to my project: https://github.com/lbignone/galaxies_datasets

**Comment by cjolowicz** [comment]
Can you trim this down into a minimal reproducible example?

Sorry for the delay, my bandwidth is somewhat limited at the moment.

**Comment by cjolowicz** [comment]
Closing for now.

Happy to reopen if you want to pursue this. Please attach the `coverage-data.zip` artifact from the coverage job, so I can reproduce your issue.
