### ISSUE TITLE
Add template variable for copyright year

### ISSUE THREAD

**Issue by cjolowicz** [cjolowicz/cookiecutter-hypermodern-python#1088]
There are two reasons for this:

- It should be possible to override the copyright year, because the time of project generation is not necessarily identical to the date of initial publication. For example, an existing project can be ported to use this project template.
- Tools that update projects with changes from their project templates should not update the copyright year. If the copyright year is stored in a template variable, this will just work. If it is embedded in the license template, it won't.

Note that copyright notices need only contain the initial date of publication (if at all). There is no need to keep an up-to-date range of years. See [TIL: You Can Stop Updating Copyright Attribution Years](https://hynek.me/til/copyright-years/).

**Comment by jasonwashburn** [comment]
Gave it a shot, glad to contribute! Open to any feedback or corrections that need to be made.
