### ISSUE TITLE
Fixture "mocker" not found

### ISSUE THREAD

**Issue by cauliyang** [cjolowicz/cookiecutter-hypermodern-python#1092]
Hi, 

I currently use `pytest` to test my module, and I use `mocker`, which need `pytest-mock` library. However, I found that the session `tests` does not install `pytest-mock`.  Hence, Actions will fail finally. 

Can we add `pytest-mock` in the template for nox session `tests` or `typeguard`

![image](https://user-images.githubusercontent.com/38903141/145325223-1cc7140a-8a3f-499c-ac5c-b11c4ab3a714.png)

**Comment by cjolowicz** [comment]
> Can we add `pytest-mock` in the template for nox session `tests` or `typeguard`

You'd also want to add it as a development dependency with Poetry.

There are many projects that don't use mocks, so I don't think that it should be added to the project template. (In fact, there are some good reasons to avoid mocks.)

**Comment by cauliyang** [comment]
Thanks for your quick response! I don't have much experience with tests, and I'm still learning about them. Today, I get a new thing ^^
