### ISSUE TITLE
Match nox sessions python version with GA on typeguard

### ISSUE THREAD

**Issue by staticdev** [cjolowicz/cookiecutter-hypermodern-python#1102]
Typeguard with `from __future__ import annontations` does not work well with older versions of Python (throwing lots of `TypeError: unsupported operand type(s) for |: 'type' and 'type'`). 

Since typeguard on GA is running only on 3.10, I suggest have the same on nox session. Also typeguard seems a bit abandoned for now, while they do not find a new [maintainer](https://github.com/agronholm/typeguard/issues/198).

**Comment by cjolowicz** [comment]
Typeguard is far from abandoned, there is active work on Typeguard 3.0.

Allowing modern type syntax by running the runtime type check only on the latest Python makes sense though, thanks!

FTR one alternative would be keeping `Union` and `Optional` type syntax. This requires adding `--keep-runtime-types` to the pyupgrade hook.

**Comment by jeeftor** [comment]
I think the hook is:

`--keep-runtime-typing`
