### ISSUE TITLE
Author not specified in docs' copyright

### ISSUE THREAD

**Issue by sgraaf** [cjolowicz/cookiecutter-hypermodern-python#1109]
Currently, the author is left as `{author}` in the copyright notice in the docs, as can be verified at the bottom of the [docs of the example instance of this cookiecutter](https://cookiecutter-hypermodern-python-instance.readthedocs.io/en/latest/).

**Comment by cjolowicz** [comment]
Thanks for catching and reporting this! That's a regression. PR welcome if you're up for it :)

**Comment by sgraaf** [comment]
Sure thing -- on it!
