### ISSUE TITLE
Add issue forms

### ISSUE THREAD

**Issue by eyllanesc** [cjolowicz/cookiecutter-hypermodern-python#1119]
- https://github.com/tiangolo/typer/tree/master/.github/ISSUE_TEMPLATE
- https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms

**Comment by cjolowicz** [comment]
Duplicate of #19 

Thanks for linking these useful resources! The typer issue template is entertaining for sure 😆
