### ISSUE TITLE
PRE_COMMIT_COLOR in tests.yml becomes PRE_COMApache-2.0_COLOR

### ISSUE THREAD

**Issue by philvarner** [cjolowicz/cookiecutter-hypermodern-python#1174]
using `cookiecutter gh:cjolowicz/cookiecutter-hypermodern-python   --checkout="2021.11.26"`

When choosing Apache 2.0 license, in the file `tests.yml`

the env var:

```
      PRE_COMMIT_COLOR: "always"
```

becomes:

```
      PRE_COMApache-2.0_COLOR: "always"
```

notice `MIT` in COMMIT

**Comment by cjolowicz** [comment]
Hi, thanks for the report! This has already been fixed in the main branch.
