### ISSUE TITLE
broken dependabot link

### ISSUE THREAD

**Issue by soxofaan** [cjolowicz/cookiecutter-hypermodern-python#1186]
https://github.com/cjolowicz/cookiecutter-hypermodern-python/blob/d54206fb34b1de8d71a3be432d21e0b1d85bbd66/README.rst#L107

This `https://dependabot.com/` link does not seem to work anymore (or is it only me?), it just forwards to github.com
```
$ curl -i https://dependabot.com/
HTTP/2 301 
content-length: 0
location: https://github.com/
```

**Comment by staticdev** [comment]
Dependabot was incorporated by Github.. the most suitable replacement I've found is:
https://github.com/dependabot/dependabot-core#dependabot
