### ISSUE TITLE
Add a makefile

### ISSUE THREAD

**Issue by Coinhexa** [cjolowicz/cookiecutter-hypermodern-python#1231]
with commands to
```
make install
make clean
make release
make docker
```
etc

**Comment by bstivers** [comment]
Other than maybe Docker, (Docker has its own way) not needed IMHO due to using Poetry for virtual env and dependency management. Makefiles are the old way of doing things, not the modern way...

**Comment by Coinhexa** [comment]
so why isnt there a Dockerfile in the project or is it scheduled for the next release?
