### ISSUE TITLE
Upload type coverage reports from mypy to Codecov

### ISSUE THREAD

**Issue by cjolowicz** [cjolowicz/cookiecutter-hypermodern-python#136]
mypy can generate coverage reports in various formats. The formats include the Cobertura XML format, which is understood by Codecov. This could be used for coverage reporting via Codecov, using a tag to distinguish it from test coverage.

**Comment by Erik-vdg** [comment]
I'm a big fan of this project, and I'm interested in working on this enhancement. Can I take it on?

**Comment by cjolowicz** [comment]
Thanks for offering to help out @Erik-vdg 💚 

This issue was created when the feature set of this project template was still very much in flow. From today's point of view, I think this feature brings little value at the cost of further increasing complexity of CI workflows. Projects built with this template already require full type coverage by virtue of running mypy in strict mode. Visualizing type coverage would be more valuable for legacy codebases with incremental typing.

I'm closing this issue for these reasons, but I'm happy to be swayed if you feel strongly about this 😉 And if you have a use case where this feature is valuable, a short howto on implementing this would be a great fit for the project wiki.

Finally, let me say that there are lots of other things to be improved, and I greatly appreciate contributions. Feel free to drop a comment on any ticket. I'll try to sort through them and mark good first issues, once I find some time.
