### ISSUE TITLE
Add GitHub Labeler Action

### ISSUE THREAD

**Issue by cjolowicz** [cjolowicz/cookiecutter-hypermodern-python#167]
For projects and the Cookiecutter itself:

- Add .github/labels.yml
- Add .github/workflows/labeler.yml

https://github.com/marketplace/actions/github-labeler
https://github.com/crazy-max/ghaction-github-labeler

Example: https://github.com/cookiecutter/cookiecutter/pull/1356/files

**Comment by oncleben31** [comment]
Is it OK if I work on a PR for this one?
