### ISSUE TITLE
Gitlab Support

### ISSUE THREAD

**Issue by e0lithic** [cjolowicz/cookiecutter-hypermodern-python#250]
Hi,

First of all thanks for the great tutorial. As someone who is just starting out with python, it was a pleasure to know and understand the best practices and devops typically used. 

I was wondering if the template could be extended for gitlab. The only concern seems to the release drafter tool which is github specific. If there are workarounds for the same, please do share.

Thanks

**Comment by cjolowicz** [comment]
Thanks for the input! 

GitLab support is certainly useful to many people (including myself). Unfortunately, I don't have the capacity to maintain GitLab support for this project template. Also, I would prefer to keep the template simple and provide as few options as possible. So a fork would seem more appropriate to me.

Personally, I use a custom version of this template with a private GitLab instance. I haven't worked out a great way to automate release notes, so I use a [CHANGELOG.md](https://keepachangelog.com/en/1.0.0/) with a little shell script called [bumpversion-changelog](https://github.com/cjolowicz/scripts/blob/master/github/bumpversion-changelog.sh). Releases are made by pushing a Git tag, using another little shell script called [bumpversion-poetry](https://github.com/cjolowicz/scripts/blob/master/github/bumpversion-poetry.sh).

**Comment by e0lithic** [comment]
Thanks for the insight. I will try to create a template and perhaps use [release-it/release-it](https://github.com/release-it/release-it) to automate the release.

**Comment by stratosgear** [comment]
Hi, I was wondering if any of you guys have done anything further with the gitlab integration.  I would be interested in following up on any potential existing work... Thanks!
