### ISSUE TITLE
Add license parameter

### ISSUE THREAD

**Issue by cjolowicz** [cjolowicz/cookiecutter-hypermodern-python#4]

**Comment by pawamoy** [comment]
Check out how I'm doing this in [cookie-poetry](https://github.com/pawamoy/cookie-poetry/blob/master/cookiecutter.json).
I basically add a choice field in cookiecutter.json with all licenses, and a folder in the template with a file for each license that gets generated. In a post-hook, I copy the selected license to the right place and delete the whole licenses folder (now useless).

**Comment by Yajo** [comment]
Yes, see https://github.com/Tecnativa/doodba-copier-template/blob/ab7a378e473ab3b15a5db811f33715024c9f2b44/%7B%25%20if%20project_license%20%25%7DLICENSE%7B%25%20endif%20%25%7D.jinja and the related stuff.

**Comment by cjolowicz** [comment]
Thanks @pawamoy and @Yajo for providing these insights!

I'm leaning towards the solution using a single license file with Jinja2 conditions because I find it more self-contained. Another example of a project template using this approach is [cookiecutter-django]. The folder solution has advantages in maintainability and readability, but I'd rather not add more logic to the hooks, and the set of supported licences won't change very often. That's my reasoning anyway, feel free to raise additional points.

[cookiecutter-django]: https://github.com/pydanny/cookiecutter-django/

Pull requests for this would be very welcome 😉
