### ISSUE TITLE
Suggestion: change README badges organization

### ISSUE THREAD

**Issue by staticdev** [cjolowicz/cookiecutter-hypermodern-python#403]
Some project with many badge tend to not use them inline. I found two other patterns that can be considered:

Table organization: https://github.com/magmax/python-inquirer/blob/master/README.rst
Multiline organization: https://github.com/dateutil/dateutil/blob/fc9b1625ebc729f01e449879b6b140abd12ae621/README.rst

Personally, I found the table organized by "groups" with same class semantics more appealing.

**Comment by cjolowicz** [comment]
Thanks for the suggestion, this is a good idea! 

I personally like the dateutil-style: It is light-weight yet more structured than what we have. They organize badges in three rows: PyPI - Docs/Support - CI. For us, maybe the following would make sense:

```rst
|PyPI| |Python Version| |License|

|Tests| |Codecov| |Read the Docs|

|pre-commit| |Dependabot| |Black|
```

They also use a different badge for Read the Docs, setting the label to "Read the Docs". I rather like that, it makes the documentation link more visible and invites the user to visit the documentation. In that case, the badge could also stand on its own, in the second row.
