### ISSUE TITLE
Dependabot is not enabled on project import

### ISSUE THREAD

**Issue by cjolowicz** [cjolowicz/cookiecutter-hypermodern-python#445]
After uploading a project with a Dependabot configuration file to GitHub, the Dependabot dashboard at *Insights > Dependency graph > Dependabot (Beta)* shows a message that Dependabot version updates aren't configured yet, and a button **Create config file**. Pressing the button opens a web editor with a sample config file, even though the config file is already present in the repository.

This happens only with a fresh test account, like in [this repository](https://github.com/cjolowicz-test/hypermodern-python/). Dependabot appears to work fine when importing from my real account, like in [this repository](https://github.com/cjolowicz/test).

**Comment by cjolowicz** [comment]
<img width="936" alt="Screenshot 2020-07-10 at 17 06 06" src="https://user-images.githubusercontent.com/653941/87169503-62839c80-c2d0-11ea-96ed-b59fe8100a9f.png">

**Comment by cjolowicz** [comment]
The import works fine on my own account: https://github.com/cjolowicz/test

However, on a fresh test account, the above behavior can be observed: https://github.com/cjolowicz-test/hypermodern-python/

**Comment by cjolowicz** [comment]
Upstream issue: https://github.com/dependabot/dependabot-core/issues/2306

**Comment by paw-lu** [comment]
FYI this seems to be working as expected now. I recently created a new project from this tempate recently, and to my surprise Dependabot started creating PRs as expected ([paw-lu/nbpreview](https://github.com/paw-lu/nbpreview)) without further modifications to `dependabot.yaml`.
