### ISSUE TITLE
Add sphinx-click

### ISSUE THREAD

**Issue by cjolowicz** [cjolowicz/cookiecutter-hypermodern-python#446]
[sphinx-click] is a Sphinx plugin that allows you to automatically extract documentation from a click-based application and include it in your docs.

[sphinx-click]: https://sphinx-click.readthedocs.io/en/latest/

This seems a good addition since we include both sphinx and click by default.

**Comment by staticdev** [comment]
@cjolowicz I am testing this one now, if you want, you can assign that to me.

**Comment by cjolowicz** [comment]
Great work 🎉  

I think it would be awesome to have this here, please go ahead 👍
