### ISSUE TITLE
Removal of codecov.yml

### ISSUE THREAD

**Issue by staticdev** [cjolowicz/cookiecutter-hypermodern-python#462]
There is no need for this file since you are not using codecov. Right?

**Comment by cjolowicz** [comment]
We're using it here:

https://github.com/cjolowicz/cookiecutter-hypermodern-python/blob/ab57909fb90ac4a7668d1b6a7c86f7965a7563d3/%7B%7Bcookiecutter.project_name%7D%7D/.github/workflows/tests.yml#L95-L97

**Comment by staticdev** [comment]
Ah, ok.. sorry then.
