### ISSUE TITLE
[Feature request] Add Prettier as pre-commit hook

### ISSUE THREAD

**Issue by pscosta5** [cjolowicz/cookiecutter-hypermodern-python#47]
I like using Prettier as a pre-commit hook for formatting Markdown and YAML files in the repo—[something like this](https://github.com/psf/black/blob/3ac97a3084544d19ffe461a06e8ec6582eccf85d/.pre-commit-config.yaml#L26-L30)

Happy to provide a PR if you're interested.

Thanks for the great template!

**Comment by cjolowicz** [comment]
A PR for this would be very welcome!

**Comment by pscosta5** [comment]
Addressed in #52 !
