### ISSUE TITLE
Unexpected behaviour with beta version numbers

### ISSUE THREAD

**Issue by oncleben31** [cjolowicz/cookiecutter-hypermodern-python#470]
Using nox for launching `tests` session I had an error with a package having a beta version lile `0.1.1-beta1`.

During the build phase the wheel created was using `0.1.0b1` version in file name.
So the following instruction in `noxfile.py` return an error:

```
   session.install(
        "--no-deps", "--force-reinstall", f"dist/{package}-{version}-py3-none-any.whl"
    )
```

Logs: 

```
nox > Running session tests-3.8
nox > Creating virtual environment (virtualenv) using python3.8 in .nox/tests-3-8
nox > poetry export --format=requirements.txt --output=/var/folders/v5/wtydb2rx72b74xds_1hc2xr80000gq/T/tmpqyo6moos/requirements.txt
nox > pip install --requirement=/var/folders/v5/wtydb2rx72b74xds_1hc2xr80000gq/T/tmpqyo6moos/requirements.txt
nox > poetry build --format=wheel
Building meteofrance-api (0.1.0-beta1)
 - Building wheel
 - Built meteofrance_api-0.1.0b1-py3-none-any.whl
nox > poetry version
nox > pip install --no-deps --force-reinstall dist/meteofrance-0.1.0-beta1-py3-none-any.whl
nox > Command pip install --no-deps --force-reinstall dist/meteofrance-0.1.0-beta1-py3-none-any.whl failed with exit code 1:
WARNING: Requirement 'dist/meteofrance-0.1.0-beta1-py3-none-any.whl' looks like a filename, but the file does not exist
ERROR: meteofrance-0.1.0-beta1-py3-none-any.whl is not a supported wheel on this platform.
nox > Session tests-3.8 failed.
```

**Comment by cjolowicz** [comment]
Thanks for the report, this is indeed a bug in the template. Poetry uses semver-style version numbers, and converts them to PEP 440-style versions on the fly when building wheels. I'm not sure yet of the best way to fix this. There are some options: 

- Perform (enough of) this conversion ourselves in the noxfile.
- Wipe out `dist` beforehand and take whatever wheel we find.
- Somehow leverage Poetry's interface to find out the exact wheel name. (Wonder what pip does when performing a PEP 517-build.)

**Comment by cjolowicz** [comment]
Thanks again for the report @oncleben31 ! Would you like to confirm if #487 fixes your issue?

**Comment by oncleben31** [comment]
fix confirmed
