### ISSUE TITLE
CONTRIBUTING files are referencing nox --session=black

### ISSUE THREAD

**Issue by oncleben31** [cjolowicz/cookiecutter-hypermodern-python#471]
The two `CONTRIBUTING.rst` file in this repo are refferencing  the command `nox --session=black``

This session name doesn't exist in any noxfile.py in the repo. The documentation needs update.

**Comment by cjolowicz** [comment]
Thank you for finding and reporting this!

The paragraph on Black should be removed from both Contributor Guides. They already mention that the Nox suite should pass, and Nox runs Black via pre-commit.

Would you like to contribute a PR for this?

**Comment by oncleben31** [comment]
I can do you want to add in contributing a recommandation to add the pre-commit-hook ?
If yes in which section ?

**Comment by cjolowicz** [comment]
> Do you want to add in contributing a recommandation to add the pre-commit-hook ?

Hm I think I'd leave that out (but feel free to convince me otherwise 😉). The pre-commit checks will also be run from Nox. I'd prefer to keep the Contributor Guide minimal and focussed on the essentials. This will also reduce duplication with the User Guide, which goes into a lot of detail.

**Comment by oncleben31** [comment]
What do you mean by User Guide. Is it the root README ? 
Because I don't see any reference on how to install the pre-commit-hook in the `{{cookiecutter.project_name}}` folder. 

As the way to install the hook is not standard (using a nox command) I think we should explain somewhere to contributors how to install it if they want to use it.

**Comment by cjolowicz** [comment]
> What do you mean by User Guide.

The User Guide is [here](https://cookiecutter-hypermodern-python.readthedocs.io/en/latest/guide.html). There's also a link to it in the Contributor Guide, under "How to test your project" (or via the "Documentation" link at the top). The section [Running pre-commit from git](https://cookiecutter-hypermodern-python.readthedocs.io/en/latest/guide.html#running-pre-commit-from-git) describes how to install the pre-commit hook.

**Comment by cjolowicz** [comment]
Oh, I just realized that you're right: the generated project does not have any information about how to install the pre-commit hook. This information is only present in the User Guide of the Cookiecutter template, which is not linked anywhere from the generated project.

So then yes 💯 ! Please do add a short note to the Contributor Guide (`{{cookiecutter.project_name}}/CONTRIBUTING.rst}}`). I would suggest to add something like the following instead of the note about `nox --session=black`:

```rst
Install pre-commit as a Git hook by running the following command:

.. code:: console

   $ nox --session=pre-commit -- install
```

**Comment by oncleben31** [comment]
OK we are aligned. I will work on the PR soon.
