### ISSUE TITLE
[Query] Multiple line Args description in docstring.

### ISSUE THREAD

**Issue by piyush-das** [cjolowicz/cookiecutter-hypermodern-python#497]
Hi,
I was trying to use this wonderful template. However, when I am trying to specify a multiple line description for an argument in the doc-string. It appears that RST301 and DAR003 are always in conflict for the following sample:
```python
def _test_func(name, func, params):
    """Transforms the given layer function into equivalent func.

    Args:
        name: Name of the layer
        func: The layer to be transformed.
        params: List containing  factorized input and output shape
            for the layer.

    Returns:
        List containing the equivalent funcs which represent the old layer.
    """
```
Now for the `params` description if I dont specify indentation I get DAR003 , and when I do specify indentation like in the above sample I get RST301. I was wondering if there is a way to resolve this conflict without doing away with one of them.

**Comment by cjolowicz** [comment]
Thank you for reporting this 👍 

Unfortunately, Google docstrings are not valid reStructuredText per se, they need to be preprocessed by the [napoleon] Sphinx extension. As it stands, `flake8-rst-docstrings` expects docstrings to be valid reStructuredText and does not perform this kind of preprocessing. So this should be considered a bug in this project template 🤔 

[napoleon]: https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html

I think you have the following options to resolve this for your project:

- Ignoring `RST301` and `RST203` (see https://github.com/peterjc/flake8-rst-docstrings/issues/17)
- Using a docstring convention that conforms to reStructuredText, such as the [NumPy] or [Sphinx] styles
- Dropping the plugin and relying on the `docs` Nox session to ensure valid markup (see also https://github.com/cjolowicz/cookiecutter-hypermodern-python/issues/461)

[NumPy]: https://numpydoc.readthedocs.io/en/latest/format.html#docstring-standard
[Sphinx]: https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html
