### ISSUE TITLE
In GA two mypy, tests and typeguard sessions are run for a given python version 

### ISSUE THREAD

**Issue by oncleben31** [cjolowicz/cookiecutter-hypermodern-python#499]
In GitHub Action we use a strategy matrix for Python versions.
With a matrix with [3.6, 3.7, 3.8], for 3.8 and 3.7 Python versions the 3.6 sessions are run too.

Example for python 3.7 item in the strategy matrix:
```
nox > Ran multiple sessions:
nox > * pre-commit: skipped
nox > * safety: skipped
nox > * mypy-3.8: skipped
nox > * mypy-3.7: success
nox > * mypy-3.6: success
nox > * tests-3.8: skipped
nox > * tests-3.7: success
nox > * tests-3.6: success
nox > * typeguard-3.8: skipped
nox > * typeguard-3.7: success
nox > * typeguard-3.6: success
```

We can reduce the duration of CI by finding a way to run only the sessions linked to the python version of the strategy matrix.

**Comment by cjolowicz** [comment]
Can you provide a link to your workflow definition?

This was fixed in [2020.6.15](https://github.com/cjolowicz/cookiecutter-hypermodern-python/releases/tag/2020.6.15), using the new Nox option `--python` to specify the target Python interpreter version. An earlier fix was merged in https://github.com/cjolowicz/cookiecutter-hypermodern-python/pull/322.

So you should be able to fix this by updating your project to a newer template version. Let me know if this does not work.

**Comment by oncleben31** [comment]
OK you are right I've missed the new tests.yml code.

Trying to retrofit it in my project, I have an error with the pre-commit hook:

```
black................................................(no files to check)Skipped
flake8...............................................(no files to check)Skipped
Check for added large files..............................................Passed
Check Toml...........................................(no files to check)Skipped
Check Yaml...............................................................Failed
- hook id: check-yaml
- exit code: 1

while constructing a mapping
  in ".github/workflows/tests.yml", line 9, column 11
found unhashable key
  in ".github/workflows/tests.yml", line 9, column 12

Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Passed
Reorder python imports...............................(no files to check)Skipped
prettier.................................................................Failed
- hook id: prettier
- files were modified by this hook

.github/workflows/tests.yml 130ms
```

It seems prettier is reformatting the code of tests.yml with something like that: 
```
  tests:
    name:
      {
        {
          "${{ matrix.session }} ${{ matrix.python-version }} / ${{ matrix.os }}",
        },
      }
    runs-on: { { "${{ matrix.os }}" } }
```

Did I miss another update to avoid this ? Or should I open a new issue ?

**Comment by cjolowicz** [comment]
You copied the template code into your project, it needs to be processed by Cookiecutter ([Jinja]). This is a Jinja template tag: `{{ "..." }}`. Inside the double quotes is the GitHub Actions expression.

The manual way to update your project (assuming it is under source control and the working directory is clean) is to re-run Cookiecutter from the parent directory using the `--overwrite-if-exists` flag. Then take a look at the diff and manually "merge" the changes.

For a less manual way, take a look at [cupper] and [cruft].

[cupper]: https://github.com/senseyeio/cupper
[cruft]: https://github.com/timothycrosley/cruft
[jinja]: https://palletsprojects.com/p/jinja/

**Comment by oncleben31** [comment]
It's obvious I feel idiot.
Thanks for your support.
You can close the issue.

**Comment by cjolowicz** [comment]
No problem :)
