### ISSUE TITLE
Move darglint config to .flake8

### ISSUE THREAD

**Issue by paw-lu** [cjolowicz/cookiecutter-hypermodern-python#518]
Hey @cjolowicz ! This project has grown so much since I was last on! Looking forward to combing through the changes.

[Darglint can read from `.flake8`](https://github.com/terrencepreilly/darglint/pull/105). The arguments in darglint can be moved to `.flake8` so that `.darglint` may be removed.

**Comment by paw-lu** [comment]
#519 implements this request.

Thanks again for the great project!

**Comment by cjolowicz** [comment]
Welcome back, @paw-lu , and thanks for your contribution!

I actually had a go at this in #453 (promptly forgot to update the docs, kudos to you for thinking of that). But then I noticed that darglint only reads its configuration from `.flake8` if invoked via flake8. When invoked as a stand-alone tool, it does not pick up the configuration settings in `.flake8`. So I think it's better not to move them. What do you think?

There is also the issue that `strictness` seems like a problematic name for a flake8 configuration option. It is overly generic and does not indicate that it is related to darglint or docstrings.

**Comment by paw-lu** [comment]
Should have searched the issues! 😅

#453 lists some good points which I'm inclined to agree with! I'll be closing #519 .

Apologies for resurfacing old issues!
