### ISSUE TITLE
[Enhancement] Add flake8-rst-docstring

### ISSUE THREAD

**Issue by pscosta5** [cjolowicz/cookiecutter-hypermodern-python#53]
I find [flake8-rst-docstring](https://github.com/peterjc/flake8-rst-docstrings) pretty useful—it checks if your docstrings are valid RST.

If there is interest I'd be happy to provide a PR.

**Comment by cjolowicz** [comment]
Yes please!

**Comment by pscosta5** [comment]
Addressed in #70.
