### ISSUE TITLE
[Enhancement] Add sphinx-autobuild option to nox's docs session

### ISSUE THREAD

**Issue by pscosta5** [cjolowicz/cookiecutter-hypermodern-python#54]
It would be useful to have the option to run `sphinx-autobuild`—where sphinx can serve your docs, open your browser, and actively watch for changes—in nox's docs session.

It could be triggered by an optional argument such as `nox -s docs -- serve`.

As always, happy to provide a PR if you are open to it.

**Comment by cjolowicz** [comment]
Yes, sounds great!

You could use [session.interactive](https://nox.thea.codes/en/stable/usage.html#forcing-non-interactive-behavior) to determine whether to run `sphinx-build` or `sphinx-autobuild`. That's also what Nox's own [noxfile.py](https://github.com/theacodes/nox/blob/f00191835f14513a9223720ee6fd3d1475485ba9/noxfile.py#L102-L106) does.

**Comment by pscosta5** [comment]
You beat me to it on #85 😅Thanks!

**Comment by cjolowicz** [comment]
Thank you for the suggestion! I hope this is what you had in mind.
