### ISSUE TITLE
Problem with Publish package on PyPI/TestPyPI on Release flow

### ISSUE THREAD

**Issue by staticdev** [cjolowicz/cookiecutter-hypermodern-python#544]
Hi,

All my projects using cookiecutter started having this error:

```
HTTPError: 403 Forbidden from https://test.pypi.org/legacy/
Invalid API Token: invalid macaroon!r
```

I generated I new token on https://test.pypi.org and it didn't solve it. I am curious, but didn't solve the problem yet.

Ex. execution: https://github.com/staticdev/pdf-split-tool/runs/1114968108

UPDATE: PyPI releases also affected.

**Comment by cjolowicz** [comment]
Hi, thanks for reporting this.

Can you try a manual upload using your API token?

```
poetry build
twine upload --verbose -r testpypi dist/*
```

Use [twine](https://twine.readthedocs.io/) with `--verbose`.

**Comment by cjolowicz** [comment]
Here is the upstream issue: https://github.com/pypa/warehouse/issues/8554

**Comment by cjolowicz** [comment]
Fix deployed upstream.

**Comment by staticdev** [comment]
Yey, it is working again. Thanks a lot!
