### ISSUE TITLE
[Query/Bug] project_name and package_name dependencies

### ISSUE THREAD

**Issue by piyush-das** [cjolowicz/cookiecutter-hypermodern-python#546]
Hi,

It seems like if the repository name and the package name are not in sync then the package doesn't get installed on doing `poetry install`. For example if the following options are used during the template configuration, the package doesn't get installed.
```bash
project_name [hypermodern-python]: hypermodern-core
package_name [hypermodern_core]: hypermodern
```

If so for the following use-case that for the same package we might have multiple variants of repositories, like hypermodern-py2 and hypermodern-py3 containing two different code bases for the same package hypermodern; what would be the best way or recommended approach? 

Thanks

**Comment by piyush-das** [comment]
@cjolowicz What's your take on the issue ?

**Comment by cjolowicz** [comment]
Hi @piyush-das thanks for the report.

If your package is not named after the project directory, you need to specify it explicitly in `pyproject.toml`:

```toml
[tool.poetry]
packages = [
    { include = "hypermodern", from = "src" },
]
```

See https://python-poetry.org/docs/pyproject/#packages

We could do this on project generation via a Jinja conditional that tests if `package_name` differs from `cookiecutter.project_name.replace('-', '_')`. Would you like to take a stab at that?

**Comment by piyush-das** [comment]
Sure, I will try to do the same over the weekend. Thanks.

**Comment by oncleben31** [comment]
Just have the issue right now and was preparing an issue. Thanks for sharing the workaround.
