### ISSUE TITLE
Rename `master` to `main`

### ISSUE THREAD

**Issue by staticdev** [cjolowicz/cookiecutter-hypermodern-python#547]
This is the new name of the base branch on Github starting on October 1st 2020. So I think it is a good idea to follow:

https://github.com/github/renaming

**Comment by cjolowicz** [comment]
We should do this when [seamless-move-for-existing-repositories](https://github.com/github/renaming#later-this-year-seamless-move-for-existing-repositories-) is implemented.

**Comment by cjolowicz** [comment]
See also #561 and #560

**Comment by staticdev** [comment]
Superb!

**Comment by cjolowicz** [comment]
This is no longer blocked and we should do this, see https://github.com/github/renaming

**Comment by staticdev** [comment]
@cjolowicz it is very easy to rename. I just did it for one of my repos, but you need to be the owner of the repo.

You go to Settings -> Branches -> Rename and voila!

It also gives you the commands to ajust the local repos:

```sh
git branch -m master main
git fetch origin
git branch -u origin/main main
```

**Comment by cjolowicz** [comment]
Thanks for the gentle nudge @staticdev  :wink: this repository is now finally using `main` as the default branch.
