### ISSUE TITLE
Switch to the MyST documentation system

### ISSUE THREAD

**Issue by cjolowicz** [cjolowicz/cookiecutter-hypermodern-python#565]
[MyST] allows you to write Sphinx documentation entirely in markdown. 

Here is a breakdown of the files that need to be converted:

The RST files under `{{cookiecutter.project_name}}`:

- The [README](https://github.com/cjolowicz/cookiecutter-hypermodern-python/blob/main/%7B%7Bcookiecutter.project_name%7D%7D/README.rst)
- The [Contributor Guide](https://github.com/cjolowicz/cookiecutter-hypermodern-python/blob/main/%7B%7Bcookiecutter.project_name%7D%7D/CONTRIBUTING.rst)
- The [Code of Conduct](https://github.com/cjolowicz/cookiecutter-hypermodern-python/blob/main/%7B%7Bcookiecutter.project_name%7D%7D/CODE_OF_CONDUCT.rst). Use the original Markdown version provided by the Contributor Covenant.
- The licenses. Should we use the original plain text versions?

The RST files under `{{cookiecutter.project_name}}/docs`:

- The wrapper files: codeofconduct.rst, contributing.rst, license.rst
- The API reference: reference.rst
- The command-line reference: usage.rst
- The index: index.rst

Converting the Cookiecutter's own documentation is tracked in a separate issue, see #1080.

[MyST]: https://myst-parser.readthedocs.io/en/latest/

**Comment by cjolowicz** [comment]
Docstrings still need to be written in reStructuredText, see https://github.com/executablebooks/MyST-Parser/issues/228.

**Comment by cjolowicz** [comment]
@cauliyang Are you still planning to work on this?

**Comment by cauliyang** [comment]
@cjolowicz, Sorry for the late reply, and I am still working on that.  Last two weeks, I am busy with my Ph.D. project. I will try my best to finish that as soon as possible next week 😃 .

**Comment by cjolowicz** [comment]
Awesome, no rush :)

I'll be working on converting the files outside the generated project (like the top-level [README](https://github.com/cjolowicz/cookiecutter-hypermodern-python/blob/main/README.rst) and the files under [docs](https://github.com/cjolowicz/cookiecutter-hypermodern-python/tree/main/docs)).

**Comment by cauliyang** [comment]
Cool,  you are responsible for lots of work ^^ .  do you think which part I should mainly focus on?  I will try my best 🚀

**Comment by cauliyang** [comment]
If I misunderstand you, please correct me.

**Comment by cjolowicz** [comment]
> do you think which part I should mainly focus on?

Let's start with your existing PR, which converts only the README. The PR should be changed so there is no option for RST: The README will always be Markdown. Does that make sense?

We can tackle the rest later.

**Comment by cjolowicz** [comment]
Updated the issue description with a breakdown of the files that need to converted.

**Comment by cauliyang** [comment]
Yep, that make sense! I can continue to convert other files under the doc to markdown. If you have any comments please free feel to tell me. It is my pleasure to contribute this project 😎
