### ISSUE TITLE
Need your expertise on a possible bug in poetry 1.1.2 with export feature.

### ISSUE THREAD

**Issue by oncleben31** [cjolowicz/cookiecutter-hypermodern-python#583]
dependabot has just push the poetry v1.1.2 but the Tests workflow shows some failures. I'm not able currently to identify if it's a poetry bug, an error in my implementation of hypermodern-python or link to the content of my package.

So first a link to the dependabot PR in my repo. You can then have access to the logs of the Nox test suite: https://github.com/hacf-fr/meteofrance-api/pull/41

The error is:

```
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    typing-extensions>=3.7.4 from https://files.pythonhosted.org/packages/60/7a/e881b5abb54db0e6e671ab088d079c57ce54e8a01a3ca443f561ccadb37e/typing_extensions-3.7.4.3-py3-none-any.whl#sha256=7cb407020f00f7bfc3cb3e7881628838e69d8f3fcab2f64742a5e76b2f841918 (from black==20.8b1->-c /tmp/tmp5dcwelq_/requirements.txt (line 16))
nox > Session pre-commit failed.
Error: Process completed with exit code 1.
```

In my package, the pyproject.toml file contain:
```
typing-extensions = {version = "^3.7.4", python = "~3.6 || ~3.7"}
```
Because i need the class TypeDict with python 3.6 and 3.7 (not for 3.8 as this class is included in typing module). It seems that black have `typing-extensions` in its dependencies  whatever the Python version. And due to my rule (which is exported in the `requirement.txt`) it raise the error above.

I've try to do a diff between the constraints export with poetry 1.0.10 and poetry 1.1.2 and I found that: 
```
299c299
< typing-extensions==3.7.4.3 \
---
> typing-extensions==3.7.4.3; python_version >= "3.6" and python_version < "3.8" \
308a309,311
```

Do some one can help me to understand the root cause and eventually a correction or a workaround ?

**Comment by cjolowicz** [comment]
IIUC you get the error because `black` depends on `typing-extensions` without a `python_version` marker. This means that pip needs to install `typing-extensions` even on Python 3.8, but it does not have a hash for it because of the `python_version` marker in your requirements.txt. (And if any package in a pip invocation has a hash, all must have one.)

You can fix this by omitting the `python` constraint in your `pyproject.toml` (and running `poetry lock --no-update` to refresh the lock file). Note that `typing-extensions` is compatible with Python 3.8 and 3.9, so there is no need for the constraint.

**Comment by oncleben31** [comment]
I agree with your explanation. And I will test the solution suggested.

The additional questions are:
- Why there is a difference between poetry v1.0.10 and v1.1.2 ? 
- Should poetry compute the unions of all python_version constraints for a given dependency ? IMO, as the package owner I master the constraint for the core package dependencies not the constraint dependencies of the development dependencies.

**Comment by cjolowicz** [comment]
I can only assume that Poetry 1.0.10 does exactly that, compute the union of the constraints. It does look like a regression in Poetry 1.1.2, so you might open an issue for them.

Repro:

```sh
poetry new example
cd example
sed -i '/^python = /s/3.8/3.7/' pyproject.toml
poetry add --python="<3.8" typing-extensions
poetry export -f requirements.txt | grep typing
poetry add --dev black
poetry export -f requirements.txt | grep typing
```

Output for Poetry 1.0.10 (Python 3.8.6):

```sh
...
typing-extensions==3.7.4.3; python_version < "3.8" \
...
typing-extensions==3.7.4.3 \
```

Output for Poetry 1.1.2 (Python 3.8.6):

```sh
...
typing-extensions==3.7.4.3; python_version < "3.8" \
...
typing-extensions==3.7.4.3; python_version < "3.8" \
```

**Comment by oncleben31** [comment]
Issue open: https://github.com/python-poetry/poetry/issues/3160

Thank you for the simple instructions for reproducing the bug.

**Comment by oncleben31** [comment]
I close the issue here and I will follow the issue on poetry repository.
