### ISSUE TITLE
Feature request: Single source the License used by the project

### ISSUE THREAD

**Issue by oncleben31** [cjolowicz/cookiecutter-hypermodern-python#607]
Is it possible to single source the license used within the project?
I'm working on a project which used the GNU GPL v3 and there are a lot of place where I have to change the name and the link to license description.

At least can we reduce the number of places where name and link are hard coded?

**Comment by oncleben31** [comment]
Oh, I miss the search before posting, The #4 is related to the same topic.
Do you want me to close my feature request?

**Comment by cjolowicz** [comment]
Thanks for the feedback. Yes, let's continue the discussion on #4 .
