### ISSUE TITLE
Docs and docs-build sessions with Python 3.9

### ISSUE THREAD

**Issue by staticdev** [cjolowicz/cookiecutter-hypermodern-python#643]
They are still using 3.8.

Needs to change:
* noxfile 
* tests workflow

**Comment by cjolowicz** [comment]
This is intentional because Read the Docs does not support Python 3.9 yet, see #603.

**Comment by staticdev** [comment]
I see @cjolowicz.. well, I tested here with 3.9 and all fine ^_^

**Comment by cjolowicz** [comment]
Yes, that's good to know, thanks!

I would propose to keep the Nox session and Tests workflow on the same Python version as Read the Docs, as that's where the documentation is ultimately built.

However, we can keep this issue open until Read the Docs upgrades to Python 3.9.

**Comment by cjolowicz** [comment]
Also thanks for already submitting the PR that will do that :+1: :100:
