### ISSUE TITLE
Problem with uploading coverage-data

### ISSUE THREAD

**Issue by staticdev** [cjolowicz/cookiecutter-hypermodern-python#644]
I am not really sure why, but I was using an [older version of this cookiecutter](https://github.com/staticdev/git-portfolio/pull/180/checks?check_run_id=1338946245) and updated a good part of it. I am not sure why do I get this error, but logs of `Upload coverage data` tell me that:

```
Run actions/upload-artifact@v2.2.0
  with:
    name: coverage-data
    path: .coverage.*
    if-no-files-found: warn
  env:
    NOXSESSION: tests
    pythonLocation: /opt/hostedtoolcache/Python/3.9.0/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.0/x64/lib
Warning: No files were found with the provided path: .coverage.*. No artifacts will be uploaded.
```

Any idea of why could this happen @cjolowicz ?

**Comment by oncleben31** [comment]
It seems you have updated the GitHub workflow for running tests nox session without updating the `noxfile.py`. The two are linked to manage code coverage.
When you are in local, code coverage is computed with all the sessions you have run in your nox call. In GitHub, all nox session are run independently so code coverage need to upload and download artefacts to be able to compute the total code coverage status.

You can check the PR #568 where this have been implemented.

**Comment by cjolowicz** [comment]
Yes. The condition `if session.interactive` added to the noxfile in #568 makes sure that during CI the coverage session is not triggered inside the tests job. Otherwise, it will combine the coverage data files, leaving nothing to upload. That leads to the warning you posted, and the failure of the coverage job in your run.

**Comment by staticdev** [comment]
Excellent, that was it @oncleben31. Thanks you both.
