### ISSUE TITLE
pre-commit version is not pinned for GitHub workflow

### ISSUE THREAD

**Issue by oncleben31** [cjolowicz/cookiecutter-hypermodern-python#645]
The workflow `pre-commit` is trying to use a pinned version of pre-commit:
`pip install --constraint=.github/workflows/constraints.txt pre-commit`

But the pre-commit version is missing in [constraint.txt file](https://github.com/cjolowicz/cookiecutter-hypermodern-python/blob/master/.github/workflows/constraints.txt)

**Comment by cjolowicz** [comment]
Thanks for reporting this!
