### ISSUE TITLE
Add `help-wanted` to Release Drafter

### ISSUE THREAD

**Issue by staticdev** [cjolowicz/cookiecutter-hypermodern-python#736]
This can be useful if you want to use `help-wanted` tag on release notes. Eg: https://github.com/staticdev/django-pagination-bootstrap/releases/tag/v2.4.4

**Comment by cjolowicz** [comment]
Thanks for the suggestion!

While I can see your use case in the project you linked, that situation appears quite exceptional. Normally, I'd use the "help wanted" tag on an open issue, not as a section in the release notes. What am I missing?

**Comment by staticdev** [comment]
@cjolowicz indeed it is not a common but more of a corner case. Projects could benefit from using release notes to show also issues that needs help. And I also like the idea of having [skip-changelog](https://github.com/cjolowicz/cookiecutter-hypermodern-python/pull/675/files) when you don't what that in release notes. Do you see any downsides of this addition besides not being frequent?

**Comment by cjolowicz** [comment]
> Projects could benefit from using release notes to show also issues that needs help. 

Ok. But for the tag to appear in the release notes, you'd need to apply it to a PR, and *merge* the PR. So I don't understand how this would show issues that need help. Can you give an example of a PR you'd want to apply this tag to?

**Comment by staticdev** [comment]
@cjolowicz you are right, in order to make that work you need to do what I did (somehow create a change on code/docs). I was intending to use this specifically to help life-cycle management in cases new maintainers are needed which is somehow common if you at some point lack of time for open-source projects. In that case, I would pin an issue saying that and also creating an alert on readme of the repo.

**Comment by cjolowicz** [comment]
Closing this as per the discussion above. As always, feel free to comment and raise additional points :)
