### ISSUE TITLE
Possible feature: nox/CI generate MO translations for generating wheels

### ISSUE THREAD

**Issue by staticdev** [cjolowicz/cookiecutter-hypermodern-python#790]
@cjolowicz not really sure if I created an issue here or on nox-poetry.

The code of [this branch](https://github.com/staticdev/human-readable/tree/times-localized) using `nox -s tests`, it does not find the folder `locale` inside my src/package_name/locale.

The thing is, if I create manually and run I get no errors:

```sh
poetry install
poetry run pytest tests/test_i18n.py
```

**Comment by cjolowicz** [comment]
￼Can you take a look if the folder is included in the wheel?￼ you did not declare it in your package configuration, and Poetry does not include it by default, because it does not contain Python code. ￼Tests with Poetry run against the source tree, not the installed wheel. That's why you only see the error with Nox.￼

**Comment by staticdev** [comment]
I thought of that too. I created a wheel with `poetry build`, then unziped it and saw the files there. But then, I double checked and saw only locale *.po files are there but not *.mo files (and I have them locally, but they are on .gitignore). Did not understand why yet, but found an interesting issue https://github.com/python-poetry/poetry/issues/2015

It might be missing a step to convert *.po into *.mo. I have to investigate further.

**Comment by cjolowicz** [comment]
I prefer to keep the scope of this project template limited to the basic infrastructure needs of most Python packages intended for PyPI. Adding support for compiling translation files, while useful, falls outside of that scope IMHO, so I'm closing this for now. I know this is somewhat subjective. As always, please feel free to continue the discussion.
