### ISSUE TITLE
[Question] Testing project against multiple versions of a  dependency.

### ISSUE THREAD

**Issue by piyush-das** [cjolowicz/cookiecutter-hypermodern-python#796]
Hi,

I was just wondering what would be the ideal way for using `nox` testing to run tests against multiple versions of a dependency to ensure compatibility. For example say we have the following in our pyproject.toml
`tensorflow-cpu = "^2.4.0"`. I understand that nox-poetry would pin this package, so let's say the poetry.lock is using the package version of `2.4.1`, however to ensure compatibility with multiple versions of the dependency i.e both `2.4.0` and `2.4.1` is there a recommended way to perform the testing ?

Thanks

**Comment by cjolowicz** [comment]
Yes, see https://github.com/cjolowicz/nox-poetry/issues/268#issuecomment-774549874
