### ISSUE TITLE
Option to have documentation on GitHub Pages, not readthedocs.io

### ISSUE THREAD

**Issue by gisandnes** [cjolowicz/cookiecutter-hypermodern-python#835]
I would like to have the project documentation on GitHub Pages, instead of in readthedocs.io. For a project the files that are presently in docs/_build/ should then be in docs/. There should then also be an empty .nojekyll file in docs/. The present docs/ should then have another name, like sphinx/.

The choice between using readthedocs.io and GitHub Pages could be another input parameter in cookiecutter.json of cookiecutter-hypermodern-python.

I am working on my own fork to try to solve this: https://github.com/gisandnes/cookiecutter-hypermodern-python

**Comment by Zethson** [comment]
Dear @gisandnes,

the current 1.3.0 cookietemple release (will happen very soon) contains a version of this template that has this feature.
See: https://github.com/cookiejar/cookietemple/pull/627

**Comment by cjolowicz** [comment]
Hi @gisandnes 

thanks for taking the time to open the feature request, and for working on and sharing your solution.

Unfortunately, I simply don't have the capacity to maintain several hosting options for documentation, useful as this may be. Generally, this project does not aim to provide a full-featured template with ready-made options for every use case. Rather, the vision is to provide a minimal structure that shows how the essential building blocks fit together.

I hope you understand.
