### ISSUE TITLE
Consider defaulting poetry to set up virtualenv in-project

### ISSUE THREAD

**Issue by yang** [cjolowicz/cookiecutter-hypermodern-python#846]
See discussion at https://github.com/python-poetry/poetry/issues/108.

This would just involve adding a poetry.toml file with:

```
[virtualenvs]
create = true
in-project = true
```

**Comment by cjolowicz** [comment]
There are advantages and disadvantages to this approach. I don't think it's helpful if this template provides a different default than Poetry does. If you prefer the virtualenv inside the source for all your projects, you can run this once and be done with it:

```
poetry config virtualenvs.in-project true
```

There is no need to enforce this for other people working on your project, who may have different preferences.
