### ISSUE TITLE
Consider install nox, nox-poetry as dev dependencies

### ISSUE THREAD

**Issue by yang** [cjolowicz/cookiecutter-hypermodern-python#847]
I believe users currently need to install this separately—wasn't sure if there was rationale for excluding this.

**Comment by cjolowicz** [comment]
Hi @yang it's a good question, and one that comes up every now and then.

There are pros and cons. Pros would be: 

- You only need a single command to install everything.
- You can pin the Nox version used with a project, even locally by other developers. (It's already pinned in CI by other means.)

Here are some disadvantages:

- Poetry's resolver currently only knows a single set of dependencies, so adding nox and nox-poetry will further constrain the dependencies of your package.
- Poetry and Nox both manage environments for a project, which makes them conceptually part of the global development environment.
- Deeply nesting Python executions and virtual environments creates complexity. You'd be running, say, pytest in a Nox environment, which was created by Nox from a Poetry environment, which was spawned by Poetry from wherever it was installed (pipx, get-poetry, etc).
- If a session were to use `poetry install --dev`, you'd install Nox in a Nox environment. It's fine I guess but... seems bloated?

Anyway I'm not sure there's a clear winner here. If you decide to go with Nox inside Poetry, let me know how it works for you. Also, if separate dependency sets ever become a thing in Poetry, that would also be a reason to reconsider this choice.
