### ISSUE TITLE
safety flagging urllib3

### ISSUE THREAD

**Issue by yang** [cjolowicz/cookiecutter-hypermodern-python#848]
(This amazing cookiecutter. Thank you.)

If you set up a new project and run nox, `safety` seems to flag urllib3, which is somewhere in the dependency chain.... Something may need to be updated, but (new to this tooling ecosystem) not sure what yet.

**Comment by cjolowicz** [comment]
Hi @yang, thanks for reporting. This was fixed in main, see #843 .
