### ISSUE TITLE
Black and python-reorder-imports have conflicting styles

### ISSUE THREAD

**Issue by benjamindkilleen** [cjolowicz/cookiecutter-hypermodern-python#983]
When importing multiple objects from a repository, black prefers this multi-line style:

```
from typing import (
    Any,
    Dict,
    Generic,
    List,
    Mapping,
    Optional,
    Set,
    TypeVar,
    Union,
    final,
)
```

Which would be preferable. However, python-reorder-imports corrects this to:

```
from typing import Any
from typing import Dict
from typing import final
from typing import Generic
from typing import List
from typing import Mapping
from typing import Optional
from typing import Set
from typing import TypeVar
from typing import Union
```

every time the pre-commit runs. This leads to a constant back and forth between the two, since my editor autoformats with black, and the pre-commit runs reorder imports after black.

Thoughts? I couldn't find a way to disable this behavior on one or the other, except for `# noreorder`, but that is inelegant.

**Comment by cjolowicz** [comment]
Black would not rewrite your second example into the first one, as it [generally preserves the AST](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#ast-before-and-after-formatting).

Maybe your editor is configured to reorder imports using [isort](https://pycqa.github.io/isort/)?

The advantage of the second style is that it reduces merge conflicts.

**Comment by benjamindkilleen** [comment]
Wow, thanks for the quick response! Your suspicion was correct; my bad. I disabled isort in my editor and it works fine now.

Reducing merge conflicts makes sense.
