### ISSUE TITLE
noxfile causes mypy error

### ISSUE THREAD

**Issue by epenet** [cjolowicz/cookiecutter-hypermodern-python#985]
When mypy is set to warn on unreachable code, then upgrading nox from 2020.12.31 to 2021.6.12 causes a "Statement is unreachable" error on line 47
```
noxfile.py: note: In function "activate_virtualenv_in_precommit_hooks":
noxfile.py:47:9: error: Statement is unreachable  [unreachable]
            return
```

These are the culprit lines:
https://github.com/cjolowicz/cookiecutter-hypermodern-python/blob/735cf236cf914369136cdec4b8e8a85b021cd707/%7B%7Bcookiecutter.project_name%7D%7D/noxfile.py#L46-L47

This is my `mypy.ini`:
```
[mypy]
check_untyped_defs = True
disallow_any_generics = True
disallow_incomplete_defs = True
disallow_subclassing_any = True
disallow_untyped_calls = True
disallow_untyped_decorators = True
disallow_untyped_defs = True
no_implicit_optional = True
no_implicit_reexport = True
pretty = True
show_column_numbers = True
show_error_codes = True
show_error_context = True
strict_equality = True
warn_redundant_casts = True
warn_return_any = True
warn_unreachable = True
warn_unused_configs = True
warn_unused_ignores = True
```

**Comment by epenet** [comment]
I have (temporarily) added `#type: ignore` the line on my project: https://github.com/hacf-fr/renault-api/pull/310

**Comment by cjolowicz** [comment]
Right, `session.bin` used to be `Optional` in Nox, this was fixed in https://github.com/theacodes/nox/pull/378. So the two lines should now be removed.
